se actualiza SCA

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -117,6 +117,24 @@ jobs:
         name: Depcheck report
         path: ${{github.workspace}}/reports
 
+    - name: Evaluate Dependency-Check Report
+      run: |
+        critical_vulnerabilities=$(jq '[ .dependencies[].vulnerabilities[]? | select(.severity?|ascii_upcase == "CRITICAL")] | length' ${{github.workspace}}/reports/dependency-check-report.json)
+        high_vulnerabilities=$(jq '[ .dependencies[].vulnerabilities[]? | select(.severity?|ascii_upcase == "HIGH")] | length' ${{github.workspace}}/reports/dependency-check-report.json)
+        medium_vulnerabilities=$(jq '[ .dependencies[].vulnerabilities[]? | select(.severity?|ascii_upcase == "MEDIUM")] | length' ${{github.workspace}}/reports/dependency-check-report.json)
+        if [ $critical_vulnerabilities -gt 0 ] || [ $high_vulnerabilities -gt 0 ] || [ $medium_vulnerabilities -gt 0 ]; then
+          echo "::error title=SCA::Se han encontrado $critical_vulnerabilities vulnerabilidades Criticas, $high_vulnerabilities  Altas y $medium_vulnerabilities Medias."
+          exit 1
+        else
+          echo "No se han encontrado vulnerabilidades"
+        fi
+
+
+    - name: Exit if Vulnerabilities Found
+      if: failure()
+      run: exit 1  
+
+      
     - name: Upload JAR
       uses: actions/upload-artifact@master
       with:
